name: CI

on:
  push:
  pull_request:
  schedule: [cron: '0 0 * * *']

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: llvm-tools-preview
    - uses: taiki-e/install-action@cargo-hack
    - uses: taiki-e/install-action@cargo-llvm-cov

    - name: Build & run tests
      run: |
        cargo hack test --each-feature --workspace
        cargo llvm-cov --workspace --doctests --lcov --output-path=lcov.info

    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lcov.info
